### ISSUE TITLE
Trying to import SpaceWidget got React.createElement: type is invalid

### ISSUE THREAD

**Issue by bastoune** [webex/react-ciscospark#298]
I am trying to play with widgets in my reactjs application but I can't figure out how to import correctly the dependencies.

Following this doc : https://github.com/ciscospark/react-ciscospark/tree/master/packages/node_modules/@ciscospark/widget-space#jsx

I cloned the repo, and built it and  here is my "chat.jsx".

But the rendering give me the following error : 

> Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

`
 import React from 'react'
 import ReactDOM from 'react-dom'
 import SpaceWidget from './ciscospark/react-ciscospark/packages/node_modules/@ciscospark/widget-
 space';

 class Chat extends React.Component {
    constructor(props) {
        super(props);
        //
        // this.state = {
        // };
    }

    componentDidMount() {
        ReactDOM.render(
            <SpaceWidget
                accessToken="BLABVLA"
                spaceId="BLABVLA"
            />,
            document.getElementById('mySpaceWidget')
        );
    }

    // componentWillUnmount() {
    //
    // }
    //
    // componentWillReceiveProps(newProps) {
    //
    // }

    render() {
        // return null
        return <div id="mySpaceWidget"></div>
    }
}

Chat.contextTypes = {
    router: React.PropTypes.object.isRequired,
};

export default Chat
`

**Comment by bzang** [comment]
@bastoune, we're actually in the process of publishing the widgets to NPM, once that happens you'll be able to just `npm install` and import them. In the meantime, check out the simple space widget example I created in this PR: https://github.com/ciscospark/react-ciscospark/pull/301/files

**Comment by bastoune** [comment]
thanks for the reply, great news ! Do you have an approximate date for the publish ?
Thanks

**Comment by bzang** [comment]
@bastoune, we probably won't be merging that PR until we've had time to build it out a bit more. I provided it for you as a getting started example. You can also grab that branch and use that as a basis for what you're trying to build.
