### ISSUE TITLE
Video chat does not work on Android tablet / phone

### ISSUE THREAD

**Issue by sueess** [webex/react-ciscospark#566]
I embedded the space widget into my website. I tried to make a video call. This works well on my MacBook using Chrome.

I tried the same on my Samsung Galaxy S7 and my Samsung Galaxy Tab A (2016) using Chrome again. While I see myself on the tablet/phone, does the counterpart only hear my voice, but not see any video. I couldn't find any suspicious log in the chrome devtools.

**Comment by adamweeks** [comment]
@sueess thanks for reporting, we are currently only developing and testing against desktop browsers, but mobile browser support is on our near timeline.
