### ISSUE TITLE
There should be an upper limit for attachments size

### ISSUE THREAD

**Issue by KamilSzostak** [webex/react-ciscospark#703]
I keep adding attachments and there seems to be no upper limit. When I finally hit send, only the first file was uploaded, all others were never shared and they are showing up as empty gray squares in the conversation window.

**Comment by bzang** [comment]
Thanks for reporting this issue @KamilSzostak, we'll look into this. In the mean time, if you have a suggestion for a fix, please don't hesitate to open a PR!

**Comment by adamweeks** [comment]
This will be resolved by #873
